services:
  mysql:
    image: mysql:8.0
    container_name: simona_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sym64simona
      MYSQL_USER: simona
      MYSQL_PASSWORD: simona123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - simona_network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      DATABASE_URL: "mysql://simona:simona123@mysql:3306/sym64simona?serverVersion=8.0"
    networks:
      - simona_network
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - simona_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"    # folosim 8081 pentru că 8080 este folosit de nginx
    environment:
      PMA_HOST: mysql
      PMA_USER: simona
      PMA_PASSWORD: simona123
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - simona_network

volumes:
  mysql_data:

networks:
  simona_network:
    driver: bridge 