version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - simona_network
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    ports:
      - "8888:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - simona_network

  mysql:
    image: mysql:8.0
    container_name: simona_mysql
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sym64simona
      MYSQL_USER: simona
      MYSQL_PASSWORD: simona123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - simona_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mysql_data:
    name: simona_mysql_data

networks:
  simona_network:
    name: simona_network