# config/routes.yaml

controllers:
    resource:
        path: '../src/Controller/'
        namespace: App\Controller
    type: attribute

# Homepage route
homepage:
    path: /
    controller: App\Controller\DefaultController::index

# Security routes
security_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

# Section routes
section_index:
    path: /sections
    controller: App\Controller\SectionsController::index

section_new:
    path: /sections/new
    controller: App\Controller\SectionsController::new

section_edit:
    path: /sections/{id}/edit
    controller: App\Controller\SectionsController::edit

section_delete:
    path: /sections/{id}
    controller: App\Controller\SectionsController::delete
    methods: [DELETE]

# Article routes
article_index:
    path: /articles
    controller: App\Controller\ArticleController::index

article_new:
    path: /articles/new
    controller: App\Controller\ArticleController::new

article_edit:
    path: /articles/{id}/edit
    controller: App\Controller\ArticleController::edit

article_delete:
    path: /articles/{id}
    controller: App\Controller\ArticleController::delete
    methods: [DELETE]

article_show:
    path: /articles/{slug}
    controller: App\Controller\ArticleController::show
